
#BARALHO.py
VALORES_PADRAO = {
    "A": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "10": 10,
    "J": 11,
    "Q": 12,
    "K": 13
}
NAIPES = [
    "copas",
    "espadas",
    "ouros",
    "paus"
]
BONUS_TRUNFO = 1000


#CLASSES.py
LIMITE_TURNO = 60 
LIMITE_OFFLINE = 30
EM_PRODUCAO = False
NOME_PADRAO = "Jogador"
NUMERO_DE_CARTAS_PADRAO = 52
VALOR_AS = 14
MAX_JOGADORES = 10
MIN_JOGADORES = 2
BYTES_TOKEN_SESSAO = 16
COOKIE_SAMESITE = "lax"
BONUS_ACERTO_PALPITE = 1

#ENDPOINTS.py
INTERVALO_VIGIA = 5
LIMITE_SALA_INATIVA = 1800
ALFABETO =  "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
TAMANHO_CODIGO_SALA = 5
MAX_SALAS = 20
MAX_TAMANHO_NOME = 20
MIN_TAMANHO_NOME = 1
N_RODADAS_PADRAO = 5
HOST = "0.0.0.0"
PORTA_PADRAO = 8000
